from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from io import BytesIO

class PDFMaker:
    def __init__(self):
        self.styles = getSampleStyleSheet()

    @staticmethod
    def __add_footer(canvas, doc):
        canvas.drawCentredString(300, 20, "Generated by AI Planner")

    @staticmethod
    def __clean_text(text):
        if not isinstance(text, str):
            return text

        return (
            text
            .replace("–", "-")
            .replace("—", "-")
            .replace("‑", "-")
            .replace("“", '"')
            .replace("”", '"')
            .replace("’", "'")
            .replace("\u2022", "-")  # bullet
            .encode("ascii", "ignore")
            .decode("ascii")
        )

    def generate_pdf_content(self, data):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        elements = []

        title_style = self.styles["Heading1"]
        section_style = self.styles["Heading2"]
        body_style = self.styles["BodyText"]

        wrap = body_style  # alias for readability

        # --- Title ---
        elements.append(Paragraph("AI-Generated Marketing Plan", title_style))
        elements.append(Spacer(1, 16))

        # --- 1. Campaign Overview ---
        elements.append(Paragraph("1. Campaign Overview", section_style))
        overview = data["campaign_overview"]

        for key, value in overview.items():
            elements.append(
                Paragraph(
                    self.__clean_text(f"<b>{key.replace('_', ' ').title()}:</b> {value}"),
                    wrap
                )
            )
            elements.append(Spacer(1, 8))

        elements.append(Spacer(1, 16))

        # --- 2. Marketing Timeline ---
        elements.append(Paragraph("2. Marketing Timeline", section_style))

        timeline_data = [["Week", "Action"]]

        for item in data["marketing_timeline"]:
            timeline_data.append([str(item["week"]), Paragraph(self.__clean_text(item["action"]), wrap)])

        timeline_table = Table(timeline_data, colWidths=[60, 360])

        timeline_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2E3B4E")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))

        elements.append(timeline_table)

        elements.append(Spacer(1, 16))

        # --- 3. Execution Workflow ---
        elements.append(Paragraph("3. Execution Workflow", section_style))

        for i, step in enumerate(data["execution_workflow"], start=1):
            elements.append(
                Paragraph(f"{i}. {self.__clean_text(step)}", wrap)
            )
            elements.append(Spacer(1, 4))

        elements.append(Spacer(1, 16))

        # --- 4. Channel Strategy ---
        elements.append(Paragraph("4. Channel Strategy", section_style))

        # -------- ORGANIC --------
        elements.append(Paragraph("Organic", self.styles["Heading3"]))

        organic_data = [["Channel", "Content", "Frequency", "Example"]]

        for ch in data["channel_strategy"]["organic"]:
            organic_data.append([
                Paragraph(self.__clean_text(ch["channel"]), wrap),
                Paragraph(self.__clean_text(ch["content_type"]), wrap),
                Paragraph(self.__clean_text(ch["frequency"]), wrap),
                Paragraph(self.__clean_text(ch["example"]), wrap),
            ])

        organic_table = Table(
            organic_data,
            colWidths=[80, 120, 100, 200]
        )

        organic_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2E3B4E")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ]))

        elements.append(organic_table)

        # -------- PAID --------
        elements.append(Spacer(1, 10))
        elements.append(Paragraph("Paid", self.styles["Heading3"]))

        paid_data = [["Platform", "Format", "Targeting", "Budget"]]

        for ad in data["channel_strategy"]["paid"]:
            paid_data.append([
                Paragraph(self.__clean_text(ad["platform"]), wrap),
                Paragraph(self.__clean_text(ad["ad_format"]), wrap),
                Paragraph(self.__clean_text(ad["targeting"]), wrap),
                Paragraph(self.__clean_text(ad["budget"]), wrap),
            ])

        paid_table = Table(
            paid_data,
            colWidths=[80, 100, 250, 70]
        )

        paid_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2E3B4E")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ]))

        elements.append(paid_table)

        elements.append(Spacer(1, 16))

        # --- 5. Conversion Strategy ---
        elements.append(Paragraph("5. Conversion Strategy", section_style))

        conv = data["conversion_strategy"]

        elements.append(
            Paragraph(
                f"<b>Booking Method:</b> {self.__clean_text(conv['booking_method'])}",
                wrap
            )
        )

        elements.append(Spacer(1, 6))
        elements.append(Paragraph("<b>Call To Action</b>", self.styles["Heading3"]))
        elements.append(Paragraph(self.__clean_text(conv["cta"]["text"]), wrap))

        elements.append(Spacer(1, 6))
        elements.append(Paragraph("<b>Urgency Tactics:</b>", wrap))

        for tactic in conv["urgency_tactics"]:
            elements.append(Paragraph(f"• {self.__clean_text(tactic)}", wrap))

        elements.append(Spacer(1, 16))

        # --- 6. Content Ideas ---
        elements.append(Paragraph("6. Content Ideas", section_style))

        for idea in data["content_ideas"]:
            elements.append(
                Paragraph(f"<b>{self.__clean_text(idea['title'])}</b>", self.styles["Heading3"])
            )
            elements.append(Paragraph(self.__clean_text(idea["description"]), wrap))
            elements.append(Spacer(1, 6))

        # Build PDF
        doc.build(
            elements,
            onFirstPage=self.__add_footer,
            onLaterPages=self.__add_footer
        )

        buffer.seek(0)
        return buffer.getvalue()
